before_script:
  - apt-get update
  - apt-get install -y libstdc++-4.9-dev g++
  - cabal update

test:7.10:
  image: haskell:7.10
  script:
    - cabal install --enable-test --enable-bench --only-dep -j
    - cabal build
    - cabal test
    - cabal bench

test:7.8:
  image: haskell:7.8
  script:
    - cabal install --enable-test --enable-bench --only-dep -j
    - cabal build
    - cabal test
    - cabal bench
